name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: thedo32/thedo32@main
        with:
          WAKATIME_API_KEY: ${{ 'waka_a2c9de4c-39b3-4bf6-b94c-d629e0749a8b' }}
          GH_TOKEN: ${{ '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' }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
